Merge Michael's branch to cxone-dev
hubadr/jenkins-library pull request #1
Opened 2023-02-15 11:32 UTC by hubadr

2023-02-15 11:43 UTC, hubadr reviewed
It is a partial first review, I still need to review the code.

2023-02-15 11:43 UTC, hubadr commented on build.bat
> +go build -gcflags "all=-N -l" -o piper.exe
I think this file has been committed by mistake. Could you remove it?

2023-02-15 11:43 UTC, hubadr commented on run.bat
> +c:\work\code\jenkins-library\piper.exe checkmarxOneExecuteScan --customConfig="c:\work\code\piper-pipelines\michael_config.yml"
I think this file has been committed by mistake. Could you remove it?

2023-02-15 11:43 UTC, hubadr commented on vars/checkmarxOneExecuteScan.groovy
> +                        [type: 'token', id: 'checkmarxOneAPIKey', env: ['PIPER_APIKey']]]
Is it working for OIDC as well?

2023-02-15 11:43 UTC, hubadr commented on resources/metadata/checkmarxOneExecuteScan.yaml
> +metadata:
I do not think that all parameters listed here are already implemented. Isn't it? 
Can we indicate with a comment which parameters are TODO?

2023-02-28 13:33 UTC, hubadr commented on resources/metadata/checkmarxOneExecuteScan.yaml
> +        default: "Checkmarx Default"
Preset is specific to the project, we cannot provide a default value. The preset is mandatory if the project does not exist and should be created. But if the project already exists, then Piper should use the value define in Checkmarx config. If the preset define in piper config is different from the one defined in Checkmarx, piper should update the project config in Checkmarx

2023-03-02 15:43 UTC, michaelkubiaczyk commented on build.bat
> +go build -gcflags "all=-N -l" -o piper.exe
I figured out how to add comments (was not logged in) - agree and removed

2023-03-02 15:43 UTC, michaelkubiaczyk commented on run.bat
> +c:\work\code\jenkins-library\piper.exe checkmarxOneExecuteScan --customConfig="c:\work\code\piper-pipelines\michael_config.yml"
Removed file

2023-03-02 15:43 UTC, michaelkubiaczyk commented on resources/metadata/checkmarxOneExecuteScan.yaml
> +metadata:
Marked with a [not yet implemented]

2023-03-02 15:44 UTC, michaelkubiaczyk commented on cmd/checkmarxOneExecuteScan.go
> +	} else if len(projects) > 1 {
Projects call can match multiple projects as the search is not exact but as a substring. Current behavior is: iterate through all matches, if one is an exact match choose that project, otherwise return the first match.

2023-03-02 15:44 UTC, michaelkubiaczyk commented on pkg/checkmarxone/checkmarxone.go
> +	// TODO - does this work?
Removed

2023-03-02 15:44 UTC, michaelkubiaczyk commented on pkg/checkmarxone/checkmarxone.go
> +// TODO - results are different in Cx1 and it is not a "ResultStatistics" object
Removed comment

2023-03-02 15:44 UTC, michaelkubiaczyk commented on pkg/checkmarxone/checkmarxone.go
> +// TODO
Removed comment

2023-03-02 15:44 UTC, michaelkubiaczyk commented on pkg/checkmarxone/checkmarxone.go
> +	// Note: this list includes API Key/service account users from Cx1, remove the /admin/ for regular users only.
Removed comment - it was indeed erroneous post

2023-03-02 15:46 UTC, michaelkubiaczyk commented on pkg/checkmarxone/checkmarxone.go
> +func (sys *SystemInstance) GetShortDescription(scanID int, pathID int) (ShortDescription, error) {
I removed the comment, but will check regarding the old SARIF part - but the description is now included in the results json returned by API so should not be needed to fetch it separately.

2023-03-02 15:46 UTC, michaelkubiaczyk commented on pkg/checkmarxone/checkmarxone.go
> +// TODO
Removed comment - todo was old

2023-03-02 15:46 UTC, michaelkubiaczyk commented on cmd/checkmarxOneExecuteScan.go
> +	//log.Entry().Info("Test - reportToInflux entry")
Removed comment

2023-03-02 15:46 UTC, michaelkubiaczyk commented on cmd/checkmarxOneExecuteScan.go
> +	//log.Entry().Info("Test - enforceThresholds entry")
Removed comment

2023-03-02 15:47 UTC, michaelkubiaczyk commented on cmd/checkmarxOneExecuteScan.go
> +	// unclear if this step is required, currently
Removed comment

2023-03-02 15:47 UTC, michaelkubiaczyk commented on cmd/checkmarxOneExecuteScan.go
> +	//log.Entry().Info("Test - verifyCxProjectCompliance entry")
Removed comment

2023-03-02 15:47 UTC, michaelkubiaczyk commented on cmd/checkmarxOneExecuteScan.go
> +	// Todo GroupId - see run_scan()
Agree it is fine now, but I see that this has a "checkmarx" and not "checkmarxOne" @hubadr should it be checkmarxone?

2023-03-02 15:48 UTC, michaelkubiaczyk commented on cmd/checkmarxOneExecuteScan.go
> +			// Review the change below - how does .FalsePositive work in old SAST XML, original line:
Removed comment

2023-03-02 15:48 UTC, michaelkubiaczyk commented on cmd/checkmarxOneExecuteScan.go
> +	//log.Entry().Errorf("Test - LOC %d, files %d", resultMap["LinesOfCodeScanned"], resultMap["FilesScanned"])
Removed comment

2023-03-02 15:48 UTC, michaelkubiaczyk commented on cmd/checkmarxOneExecuteScan.go
> +	//log.Entry().Infof("Test - getDetailedResults entry with %d results", len(results))
Removed comment

2023-03-28 11:51 UTC, thtri requested changes

2023-03-28 11:51 UTC, thtri commented on pkg/checkmarxone/reporting.go
> +	if s, err := strconv.ParseInt(fmt.Sprint((*data)["ProjectId"]), 10, 64); err == nil {
No longer need to convert Int to Str since ProjectId in Cx1 is alredy a string 
```suggestion
	ProjectId: fmt.Sprint((*data)["ProjectId"])
```

2023-03-28 11:51 UTC, thtri commented on pkg/checkmarxone/reporting.go
> +	if s, err := strconv.ParseInt(fmt.Sprint((*data)["ScanId"]), 10, 64); err == nil {
No longer need to convert Int to Str since ScanID in Cx1 is already a string
```suggestion
	ScanID: fmt.Sprint((*data)["ScanID"])
```

2023-03-30 07:59 UTC, thtri commented on cmd/checkmarxOneExecuteScan.go
> +		branch = fmt.Sprintf("PR-%v-%v", c.config.PullRequestName, c.config.Branch)
We can remove "PR" prefix. In this code https://github.wdf.sap.corp/ContinuousDelivery/piper-library/blob/master/vars/sapPiperStagePRVoting.groovy#L379, `pullRequestName: env.BRANCH_NAME` is sent to the step. In case of PRs, the `env.BRANCH_NAME` will be prefixed already, something like PR-123

2023-03-30 08:17 UTC, michaelkubiaczyk commented on cmd/checkmarxOneExecuteScan.go
> +	// Maybe we can set the branch even for zipUpload scans, Michael will check.
Done

2023-03-30 08:19 UTC, michaelkubiaczyk commented on cmd/checkmarxOneExecuteScan.go
> +	//options := piperHttp.ClientOptions{MaxRetries: config.MaxRetries}
done

2023-03-30 08:24 UTC, michaelkubiaczyk commented on cmd/checkmarxOneExecuteScan.go
> +	if c.config.VulnerabilityThresholdEnabled {
Based on our discussion, this will remain as-is (linked to "VerifyOnly" config) for discussion with Sven.

2023-03-30 08:24 UTC, michaelkubiaczyk commented on cmd/checkmarxOneExecuteScan.go
> +	if insecure {
Same as above, to discuss with Sven

2023-03-30 08:31 UTC, michaelkubiaczyk commented on pkg/checkmarxone/reporting.go
> +	if s, err := strconv.ParseInt(fmt.Sprint((*data)["ProjectId"]), 10, 64); err == nil {
Done

2023-03-30 08:31 UTC, michaelkubiaczyk commented on pkg/checkmarxone/reporting.go
> +	if s, err := strconv.ParseInt(fmt.Sprint((*data)["ScanId"]), 10, 64); err == nil {
Done

2023-03-30 08:35 UTC, michaelkubiaczyk commented on cmd/checkmarxOneExecuteScan.go
> +	err = c.GetReportJSON(&detailedResults)
To do - incl. check for legacy XML report code

2023-03-30 08:45 UTC, michaelkubiaczyk commented on cmd/checkmarxOneExecuteScan.go
> +		branch = fmt.Sprintf("PR-%v-%v", c.config.PullRequestName, c.config.Branch)
Done - PR removed

2023-03-31 07:41 UTC, michaelkubiaczyk commented on cmd/checkmarxOneExecuteScan.go
> +	jsonReport := checkmarxOne.CreateJSONReport(detailedResults)
@thtri - should the new GetReportJSON be called at the same point as GetHeaderReportJSON? Or should there be a generateJsonReport flag in the pipeline config?

2023-03-31 07:55 UTC, thtri commented on cmd/checkmarxOneExecuteScan.go
> +	jsonReport := checkmarxOne.CreateJSONReport(detailedResults)
@michaelkubiaczyk for consistency, GetReportJSON can be at the same point of GetReportPDF (so same as GetHeaderReportJSON). For me, JSON replaces XML, no need a new flag. If users really want, it can be added later.

2023-03-31 08:26 UTC, merged